### ISSUE TITLE
How to list Token on Decentrex? Who to contact?

### ISSUE THREAD

**Issue by BTCEtoken** [decentrex/decentrex.github.io#22]

**Comment by ethereumdevs** [comment]
Hi,
First, you can trade any token vs any token or Ethereum, using token address:
https://decentrex.com/#TOKEN_ADDRESS-ETH
To list token with an official ticker you just need to ask here or in Twitter.
Thank you for using Decentrex decentralized cryptocurrency exchange.

**Comment by BTCEtoken** [comment]
Can you list our Token, EthereumBitcoin, symbol BTCE and contract address and all details on website:
www.btcetoken.com

Please let us know once listed so we can let the world know.

Best!

**Comment by BTCEtoken** [comment]
Could you list our token with an official ticker and let us know so we can inform the world.
Thanks in advance.

EthereumBitcoin (BTCE) will be on many exchanges soon (2 now, and many in process) and
it will be heavily promoted in the mass media, so many trades in the future will come by 
listing our cryptocurrency on your exchange.

Thanks in advance.

website: www.btcetoken.com

Contract address and all info there too.

Name: EthereumBitcoin
Symbol: BTCE
Supply: 21,000,000

Decimals: 8

Contract Address:
0x0886949c1b8C412860c4264Ceb8083d1365e86CF

**Comment by 888-Token** [comment]
Could you please add our token to your Exchange?

Token name: 888

Token symbol: 888

Token Decimals: 18

Contract Address: 0x87d9bF506B434e9973cb0e6183DA7A50A16796b2

Website: http://888token.xyz

888 Lucky Charm Tokens | limited to 888M Tokens

**Comment by ethereumdevs** [comment]
Will be added in next update soon.

**Comment by decentrex** [comment]
Next update

**Comment by litecoindiamond** [comment]
.
