### ISSUE TITLE
adding Ethereum Movie Venture Token EMV

### ISSUE THREAD

**Issue by Bingo123123123** [decentrex/decentrex.github.io#4]
Is it possible to add ERC-20 certified EMV Token of the Ethereum Movie Venture project that produces the worlds first Ethereum funded movie?

https://coinmarketcap.com/assets/ethereum-movie-venture/

the website is https://emovieventure.com with this token here:
https://ethplorer.io/address/0xb802b24e0637c2b87d2e8b7784c055bbe921011a

with social feeds 
https://www.facebook.com/ThePittsCircus
https://twitter.com/pitts_circus
https://twitter.com/emovieventure
https://www.facebook.com/eMovieVenture

thanks so much in advance.

**Comment by decentrex** [comment]
Thank you
