### ISSUE TITLE
Need help with decimal for token contract

### ISSUE THREAD

**Issue by btcmacroecon** [decentrex/decentrex.github.io#6]
Dear Decentrex, 
I appreciate your decentralization and model. But I have a problem in listing in that my token balance is showing up incorrect. 
0xf77089f2f00fca83501705b711cbb10a0de77628 is the original token contract.
The decimal should be 0. It is correct at Parity.io and via Etherscan. So I'm not sure who to ask for help! I think this is showing up as 8?? 0 is correct to get correct balance.
Thanks in advance for help and let me know if you need more info~

**Comment by decentrex** [comment]
Hi,
You token is https://etherscan.io/address/0xf77089f2f00fca83501705b711cbb10a0de77628#readContract

1.  name    BTCMACROECON string
--
2.  totalSupply    50000000 uint256
**3.  decimals    8 uint8**
4.  version    H0.1 string
5.  balanceOf

Currently your token is not "listed" on decentrex as an official trading pair with an address https://decentrex.com/#BMG-ETH
So there are no settings on the side on Decentrex to change about decimals value.
You still can trade at 
https://decentrex.com/#0xf77089f2f00fca83501705b711cbb10a0de77628-ETH

Also you can trade your token vs ANY other ETH based token with
https://decentrex.com/#0xf77089f2f00fca83501705b711cbb10a0de77628-OTHER-TOKEN-SMART-CONTRACT-ADDRESS

**Comment by btcmacroecon** [comment]
thank you!

**Comment by btcmacroecon** [comment]
0xf77089f2F00fca83501705b711Cbb10a0De77628

Hello! Testing and trying to trade at Decentrex. My trades aren't showing
up, this happened several times in July and I proved that and you verified
that was a bug. Well my trades are not going through.
Also, I am concerned about consistency as I am testing and trying to get
balance to show up correctly. I go to other because you won't list it,
fine. But when I try 0 as decimal point (which would show the correct
balance), it does not show correct balance. I test with 8 still not correct
balance, so that doesn't fix it. Oddly enough I have been able to replicate
the correct balance, only a few times.. I go back and forth....but there
seems to be no consistency. What do I need to do to get this correct and
can I please request to be listed? If not why not? I'd like an answer, you
have many alts on there. So I am trying to ask in decentral way versus
central authority of censoring some but letting others trade decentrally,
yet there appears to bugs or something inconsistent.
I realize there was problem with decimal. Balance shows correct at Parity,
Etherscan fixed the problem, My MEW wallet works with 0 for correct
balance. I tell others this, yet when I try to change at Decentrex be it 0
or 8 decimals it's still wrong. And beyond that again, orders not showing
up. I've tried with AMIS and ETH.
Obviously I;d like to trade there, obviously I am testing this to get it
right, but I could please use some help.
Please help and I'd like to get some tokens up here trading. Thx. I could
also offer some for giveaways to try and get people to try out Decentrex? I
am trying that anyway, but if in test and doesnt work, its a huge waste of
time for everybody.
